#!/bin/sh
output_dir=`dirname $1`
filename=${1%.*}

if pdflatex -interaction=nonstopmode -output-directory=$output_dir $filename.tex > /dev/null; then
  convert -density 300 $filename.pdf -resize 960 -flatten $filename.jpg
  open $filename.jpg
  echo "OK"
else
  echo "Failed to compile"
fi
